# Generated by Django 2.0.9 on 2018-10-19 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=2000)),
                ('flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'mgenre',
            },
        ),
        migrations.CreateModel(
            name='MIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('addr', models.CharField(db_index=True, max_length=255)),
                ('flag', models.IntegerField(default=1)),
                ('mgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MGenre')),
            ],
            options={
                'db_table': 'midata',
            },
        ),
        migrations.CreateModel(
            name='MIGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=2000)),
                ('flag', models.IntegerField(default=1)),
                ('mgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MGenre')),
            ],
            options={
                'db_table': 'migenre',
            },
        ),
        migrations.CreateModel(
            name='MInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sorce', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=500)),
                ('ptime', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=200)),
                ('pyear', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('img', models.CharField(blank=True, max_length=2000)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('activator', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('mtype', models.ManyToManyField(to='movie.MGenre')),
            ],
            options={
                'db_table': 'minformation',
            },
        ),
    ]
